name: Build Brave for macOS

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 180

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'export PATH="/opt/homebrew/bin:$PATH"' >> ~/.zshrc
        source ~/.zshrc
        brew install python@3.11 node@20 git ninja pkg-config
        brew link --force python@3.11 node@20
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH

    - name: Sync and build
      run: |
        fetch --nohooks brave
        cd src
        gclient sync --verbose
        gn gen out/Release --args="is_debug=false symbol_level=0"
        autoninja -C out/Release brave -j 4

    - name: Upload artifact
      uses: actions/upload-artifact@v4  # 关键修改点
      with:
        name: brave-macos-build
        path: src/out/Release/Brave Browser.app
